#!/bin/bash
rsync -avz --exclude=.sass_cache /home/donny/projects/fortnebula.com/_site/ /home/donny/projects/donnydavis.github.io/
cd /home/donny/projects/donnydavis.github.io/
git add -A
git commit -m "auto deploy"
git push https://donnydavis:1BADnancy**@github.com/donnydavis/donnydavis.github.io --all
